"""add-last_match_is_success_column-to-user

Revision ID: 0d142606b2ff
Revises: cf228d199812
Create Date: 2025-07-12 01:30:12.808138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d142606b2ff'
down_revision: Union[str, Sequence[str], None] = 'cf228d199812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_match_is_success', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_match_is_success')
    # ### end Alembic commands ###
